export default [
  { step: 1, name: '致学员的一封信', week: 1 },
  { step: 3, name: '关键流程问卷', week: 1 },
  { step: 4, name: '关于LMI 及LMI核心理念', week: 1 },
  { step: 5, name: '关键学习要点问卷', week: 1 },
  { step: 6, name: '自我评估表', week: 1 },
  { step: 7, name: '我的挑战表', week: 1 },
  { step: 8, name: '学员反馈表', week: 1 },
  { step: 9, name: '第二周学习流程', week: 1 },
  { step: 10, name: '了解S.M.A.R.T.目标设定', week: 2 },
  { step: 11, name: '关键学习要点问卷', week: 2 },
  { step: 12, name: '小组辅导', week: 2 },
  { step: 14, name: 'S.M.A.R.T.目标设定', week: 2 },
  { step: 13, name: '个人辅导', week: 2 },
  { step: 15, name: '学员反馈表', week: 2 },
  { step: 16, name: '第三周学习流程', week: 2 },
  { step: 17, name: '目标计划工作单', week: 3 },
  { step: 18, name: '关键学习要点问卷', week: 3 },
  { step: 19, name: '目标清单总表', week: 3 },
  { step: 39, name: '了解周目标、日计划、31日追踪', week: 3 },
  { step: 20, name: '周目标-日计划-31日追踪', week: 3 },
  { step: 21, name: '学员反馈表', week: 3 },
  { step: 22, name: '第四周学习流程', week: 3 },
  { step: 23, name: '生命之轮&月度目标计划', week: 4 },
  { step: 24, name: '关键学习要点问卷', week: 4 },
  { step: 25, name: '月度目标计划', week: 4 },
  { step: 26, name: '学员反馈表', week: 4 },
  { step: 27, name: '第五周学习流程', week: 4 },
  { step: 28, name: '使用完整的目标规划·SP', week: 5 },
  { step: 29, name: '关键学习要点问卷', week: 5 },
  { step: 30, name: '使用SP电子版目标追踪', week: 5 },
  { step: 31, name: '学员反馈表', week: 5 },
  { step: 32, name: '第六周学习流程', week: 5 },
  { step: 33, name: '整体学习回顾', week: 6 },
  { step: 40, name: '自我评估表', week: 6 },
  { step: 38, name: '关键学习要点问卷', week: 6 },
  { step: 34, name: '小组辅导', week: 6 },
  { step: 35, name: '学员整体学习评估', week: 6 },
  // { step: 36, name: '持续学习的时间及流程说明', week: 6 },
  { step: 37, name: '结业证书', week: 6 }
]
